language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - gnupg2

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/$GROUP_ID_PATH

before_install:
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh

install:
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r target/cobertura/coverage.xml
  - curl $DEPLOYER_URL/deploy.sh | bash

notifications:
  email:
    on_success: never
    on_failure: change